# Generated by Django 5.1.1 on 2024-10-04 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='gafas',
            fields=[
                ('ItemId', models.BigAutoField(primary_key=True, serialize=False)),
                ('ItemName', models.TextField(max_length=255)),
                ('ItemCategory', models.TextField(max_length=255)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bodega',
            fields=[
                ('BodegaID', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', models.TextField(max_length=100)),
                ('ItemStock', models.IntegerField()),
                ('ItemId', models.ManyToManyField(related_name='bodega_gafas', to='store.gafas')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('1', 'aprobada'), ('2', 'pendiente'), ('3', 'denegada')], default='2', max_length=1)),
                ('address', models.TextField(max_length=255)),
                ('products', models.ManyToManyField(related_name='orden_gafas', to='store.gafas')),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('WishlistID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ItemsId', models.ManyToManyField(related_name='wishlist_gafas', to='store.gafas')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]